### ISSUE TITLE
Compatible only with filesystem assetstore

### ISSUE THREAD

**Issue by msmolens** [OpenGeoscience/girder_geospatial#34]
The below function calls `fullPath()` on the assetstore adapter, but this method is implemented only for `FilesystemAssetstoreAdapter`. 
https://github.com/OpenGeoscience/girder_geospatial/blob/2796358e68c10c3d355365c6887663a197824be7/server/rest.py#L48-L51
The restriction should be documented.

**Comment by manthey** [comment]
It could be switched to `File().getLocalFilePath(girder_file)` to not have the restriction (if a girder mount is used, too).

**Comment by dorukozturk** [comment]
@msmolens This is a great point. I think using a mount and using getLocalFilePath makes more sense since we want to support shapefiles.
