### ISSUE TITLE
Unable to get geometa that was set manually 

### ISSUE THREAD

**Issue by msmolens** [OpenGeoscience/girder_geospatial#35]
If I manually set geometa using `PUT /item/{id}/geometa`, as described in "3. Creating arbitrary geospatial metadata on an existing item" in the Usage documentation, I'm unable to retrieve that geometa using `GET /item/{id}/geometa". This is counterintuitive.

The GET endpoint implementation queries the registered handlers, but never looks at an item's existing "geometa" field.

Note that the item is returned by the search endpoint `GET /item/geometa`.

**Comment by dorukozturk** [comment]
Ugh that sounds super counterintuitive. I am taking a look now.
